/**********************************************************************************************************************
 * \file ULTRA_FILT.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "ULTRA_FILT.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define WINDOW_SIZE 5

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static float32_t sensor_side_avg;
static float32_t sensor_rear_avg;
static uint32_t sensor_side_count;
static uint32_t sensor_rear_count;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void init_Ultra_Filter(void) {
    sensor_side_avg = 0.0F;
    sensor_rear_avg = 0.0F;
    sensor_side_count = 0U;
    sensor_rear_count = 0U;
}

float32_t mov_AVG_Filter(float32_t new_value, SENSOR_TYPE sensor) {
    float32_t *avg;
    uint32_t *count;

    if(sensor == SENSOR_SIDE) {
        avg = &sensor_side_avg;
        count = &sensor_side_count;
    } else {
        avg = &sensor_rear_avg;
        count = &sensor_rear_count;
    }

    if(new_value < 2.00 || new_value > 400.0) {
        return *avg;
    }

    if(*count == 0) {
        *avg = new_value;
    } else {
        *avg = *avg + (new_value - *avg) /
                (float32_t)((*count < WINDOW_SIZE) ? *count + 1 : WINDOW_SIZE);
    }

    (*count)++;

    return *avg;
}

uint32_t get_bUltra_val(float32_t maf){
    UData data;
    data.side_filtered = sensor_side_avg;
    data.rear_filtered = sensor_rear_avg;

    return data;
}
