/**********************************************************************************************************************
 * \file GTM_TIM_Capture.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "IfxGtm_Tim_In.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm_Atom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PWM_OUT         IfxGtm_ATOM1_1_TOUT10_P00_1_OUT  /* Port pin which is driven by the PWM                      */
#define PWM_IN          IfxGtm_TIM2_5_TIN15_P00_6_IN     /* Input port pin for the PWM signal                        */
#define SIDE_PWM_IN     IfxGtm_TIM2_4_TIN14_P00_5_IN

#define CLK_FREQ        1000000.0f                          /* CMU clock frequency, in Hertz                         */
#define ULT_PWM_PERIOD  100000                               /* PWM period for the ATOM, in ticks                    */
#define DUTY_CYCLE      ULT_PWM_PERIOD/2000                 /* PWM signal duty cycle for the TOM                     */


#define secTous 1000000

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
float32 g_measuredPwmDutyCycle = 0.0;                   /* Global variable for duty cycle of generated PWM signal   */
float32 g_measuredPwmFreq_Hz = 0.0;                     /* Global variable for frequency calculation of PWM signal  */
float32 g_measuredPwmPeriod = 0.0;                      /* Global variable for period calculation of PWM signal     */
IfxGtm_Tim_In g_driverTIM;                              /* TIM driver structure                                     */
boolean g_dataCoherent = FALSE;                         /* Boolean to know if the measured data is coherent         */
float32_t b_pwm_period_us;
float32_t b_pwm_sec_us;

float32 s_measuredPwmDutyCycle = 0.0;
float32 s_measuredPwmFreq_Hz = 0.0;
float32 s_measuredPwmPeriod = 0.0;
IfxGtm_Tim_In s_driverTIM;
boolean s_dataCoherent = FALSE;
float32_t s_pwm_period_us;
float32_t s_pwm_sec_us;



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* This function initializes the TIM to capture a PWM signals */
void init_TIM(void)
{
    IfxGtm_enable(&MODULE_GTM);                                         /* Enable the GTM                           */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);        /* Enable the CMU clock 0                   */

    IfxGtm_Tim_In_Config configTIM;

    IfxGtm_Tim_In_initConfig(&configTIM, &MODULE_GTM);                  /* Initialize default parameters            */
    configTIM.filter.inputPin = &PWM_IN;                                /* Select input port pin                    */
    configTIM.filter.inputPinMode = IfxPort_InputMode_pullDown;         /* Select input port pin mode               */
    IfxGtm_Tim_In_init(&g_driverTIM, &configTIM);                       /* Initialize the TIM                       */
}

void side_TIM(void){
    IfxGtm_enable(&MODULE_GTM);                                         /* Enable the GTM                           */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);        /* Enable the CMU clock 0                   */

    IfxGtm_Tim_In_Config sideTIM;
    IfxGtm_Tim_In_initConfig(&sideTIM, &MODULE_GTM);
    sideTIM.filter.inputPin = &SIDE_PWM_IN;
    sideTIM.filter.inputPinMode = IfxPort_InputMode_pullDown;
    IfxGtm_Tim_In_init(&s_driverTIM, &sideTIM);
}


/* Initialization of the TOM and generation of a PWM signal */
void generate_PWM(void)
{
    IfxGtm_Atom_Pwm_Config u_atomConfig;
    IfxGtm_Atom_Pwm_Driver u_atomDriver;

    IfxGtm_enable(&MODULE_GTM);                                             /* Enable GTM                           */

    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ);    /* Set the CMU clock 0 frequency        */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);            /* Enable the CMU clock 0               */

    IfxGtm_Atom_Pwm_initConfig(&u_atomConfig, &MODULE_GTM);                 /* Initialize default parameters        */

    u_atomConfig.atom = PWM_OUT.atom;                                         /* Select the ATOM depending on the LED     */
    u_atomConfig.atomChannel = PWM_OUT.channel;                               /* Select the channel depending on the LED  */
    u_atomConfig.period = ULT_PWM_PERIOD;                                 /* Set timer period                         */
    u_atomConfig.pin.outputPin = &PWM_OUT;                                    /* Set LED as output                        */
    u_atomConfig.synchronousUpdateEnabled = TRUE;                           /* Enable synchronous update                */
    u_atomConfig.dutyCycle = DUTY_CYCLE;

    IfxGtm_Atom_Pwm_init(&u_atomDriver, &u_atomConfig);                     /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&u_atomDriver, TRUE);                             /* Start the PWM                            */

}

/* This function measures the period, the frequency and the duty cycle of the PWM signal */
float32_t measure_PWM(void)
{
    IfxGtm_Tim_In_update(&g_driverTIM);                                         /* Update the measured data         */
    g_measuredPwmPeriod = IfxGtm_Tim_In_getPeriodSecond(&g_driverTIM);          /* Get the period of the PWM signal */
    g_measuredPwmFreq_Hz = 1 / g_measuredPwmPeriod;                             /* Calculate the frequency          */
    g_measuredPwmDutyCycle = IfxGtm_Tim_In_getDutyPercent(&g_driverTIM, &g_dataCoherent); /* Get the duty cycle     */

    b_pwm_period_us = g_measuredPwmPeriod * secTous;
    b_pwm_sec_us = b_pwm_period_us * (g_measuredPwmDutyCycle / 100);

    return b_pwm_sec_us;
}

float32_t side_PWM(void) {
    IfxGtm_Tim_In_update(&s_driverTIM);                                         /* Update the measured data         */
    s_measuredPwmPeriod = IfxGtm_Tim_In_getPeriodSecond(&s_driverTIM);          /* Get the period of the PWM signal */
    s_measuredPwmFreq_Hz = 1 / s_measuredPwmPeriod;                             /* Calculate the frequency          */
    s_measuredPwmDutyCycle = IfxGtm_Tim_In_getDutyPercent(&s_driverTIM, &s_dataCoherent); /* Get the duty cycle     */

    s_pwm_period_us = s_measuredPwmPeriod * secTous;
    s_pwm_sec_us = s_pwm_period_us * (s_measuredPwmDutyCycle / 100);

    return s_pwm_sec_us;
}
