/**********************************************************************************************************************
 * \file ASCLIN_UART.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxCpu_Irq.h"
#include "ASCLIN_UART.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define UART_BAUDRATE           9600                                  /* UART baud rate in bit/s                  */
#define UART_USB_BAUDRATE       9600

#define UART_PIN_RX             IfxAsclin0_RXB_P15_3_IN
#define UART_PIN_TX             IfxAsclin0_TX_P15_2_OUT

//LK USB UART
//#define UART_PIN_RX             IfxAsclin0_RXA_P14_1_IN
//#define UART_PIN_TX             IfxAsclin0_TX_P14_0_OUT

#define UART_USB_RX             IfxAsclin3_RXD_P32_2_IN
#define UART_USB_TX             IfxAsclin3_TX_P15_7_OUT

#define UART_TOF_RX             IfxAsclin1_RXB_P15_5_IN
#define UART_TOF_TX             IfxAsclin1_TX_P15_4_OUT

#define LED                     &MODULE_P10, 2

/* Definition of the interrupt priorities */
#define INTPRIO_ASCLIN0_RX      5     //esp
#define INTPRIO_ASCLIN0_TX      20
#define INTPRIO_ASCLIN3_RX      7     //putty
#define INTPRIO_ASCLIN3_TX      3

#define UART_RX_BUFFER_SIZE     256                                      /* Definition of the receive buffer size    */
#define UART_TX_BUFFER_SIZE     256                                      /* Definition of the transmit buffer size   */
#define SIZE                    1                                      /* Size of the string                       */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Declaration of the ASC handle */
static IfxAsclin_Asc g_ascHandle;
static IfxAsclin_Asc g_ascHandle_usb;

/* Declaration of the FIFOs parameters */
static uint8 g_ascTxBuffer[UART_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_ascRxBuffer[UART_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

/* Definition of txData and rxData */
uint8 g_txData[SIZE] = {''};
uint8 g_rxData[SIZE] = {''};

/* Size of the message */
Ifx_SizeT g_txCount = sizeof(g_txData);
Ifx_SizeT g_rxCount = sizeof(g_rxData);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Adding of the interrupt service routines */
IFX_INTERRUPT(asclin0TxISR, 0, INTPRIO_ASCLIN0_TX);
void asclin0TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_ascHandle);
}

IFX_INTERRUPT(asclin0RxISR, 0, INTPRIO_ASCLIN0_RX);
void asclin0RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&g_ascHandle);
}

IFX_INTERRUPT(asclin3TxISR, 0, INTPRIO_ASCLIN3_TX);
void asclin3TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_ascHandle_usb);
}

IFX_INTERRUPT(asclin3RxISR, 0, INTPRIO_ASCLIN3_RX);
void asclin3RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&g_ascHandle_usb);
}
/* This function initializes the ASCLIN UART module */
void init_ASCLIN_UART(void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN0);

    /* Set the desired baud rate */
    ascConfig.baudrate.baudrate = UART_BAUDRATE;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN0_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN0_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &g_ascTxBuffer;
    ascConfig.txBufferSize = UART_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &g_ascRxBuffer;
    ascConfig.rxBufferSize = UART_RX_BUFFER_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,       IfxPort_InputMode_pullUp,     /* CTS pin not used */
        &UART_PIN_RX,   IfxPort_InputMode_pullUp,     /* RX pin           */
        NULL_PTR,       IfxPort_OutputMode_pushPull,  /* RTS pin not used */
        &UART_PIN_TX,   IfxPort_OutputMode_pushPull,  /* TX pin           */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_ascHandle, &ascConfig); /* Initialize module with above parameters */

    //////////////////////////////////////////////////////////

    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig_usb;
    IfxAsclin_Asc_initModuleConfig(&ascConfig_usb, &MODULE_ASCLIN3);

    /* Set the desired baud rate */
    ascConfig_usb.baudrate.baudrate = UART_USB_BAUDRATE;

    /* ISR priorities and interrupt target */
    ascConfig_usb.interrupt.txPriority = INTPRIO_ASCLIN3_TX;
    ascConfig_usb.interrupt.rxPriority = INTPRIO_ASCLIN3_RX;
    ascConfig_usb.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig_usb.txBuffer = &g_ascTxBuffer;
    ascConfig_usb.txBufferSize = UART_TX_BUFFER_SIZE;
    ascConfig_usb.rxBuffer = &g_ascRxBuffer;
    ascConfig_usb.rxBufferSize = UART_RX_BUFFER_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins_usb =
    {
        NULL_PTR,       IfxPort_InputMode_pullUp,     /* CTS pin not used */
        &UART_USB_RX,   IfxPort_InputMode_pullUp,     /* RX pin           */
        NULL_PTR,       IfxPort_OutputMode_pushPull,  /* RTS pin not used */
        &UART_USB_TX,   IfxPort_OutputMode_pushPull,  /* TX pin           */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig_usb.pins = &pins_usb;

    IfxAsclin_Asc_initModule(&g_ascHandle_usb, &ascConfig_usb); /* Initialize module with above parameters */
}

void send_ASCLIN_UART_message(void data[], Ifx_SizeT dataSize)
{
//    IfxAsclin_Asc_write(&g_ascHandle, data, &dataSize, TIME_INFINITE);
    IfxAsclin_Asc_write(&g_ascHandle_usb, data, &dataSize, TIME_INFINITE);
}
