/**********************************************************************************************************************
 * \file Ultrasonic.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Ultrasonic.h"
#include "GTM_TIM_Capture.h"
#include "ASCLIN_UART.h"

#include "Ifx_reg.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void Init_Ultrasonics(void)
{
	/* Init Rear Ultrasonic Pin */
	//MODULE_P00.IOCR0.B.PC0 = 0x10; /* Rear TRIG */
	//MODULE_P20.IOCR0.B.PC1 = 0x2; /* Rear ECHO */

	init_TIM();
	side_TIM();
    /* Send Trigger Pulse */
    generate_PWM();
}

double ReadUltrasonic_noFilt(void)
{
	float32_t b_duration;
	float32_t b_distance;
	//uint8_t data[1];

	/* Calculate Distance */
	b_duration = measure_PWM();
	b_distance = 0.0343 * b_duration / 2.0; // cm/us

	//data[0] = (uint8_t)distance;

	//send_ASCLIN_UART_message(data, (Ifx_SizeT)1);

	return b_distance;
}
double SideUltrasonic_noFilt(void) {
    float32_t s_duration;
    float32_t s_distance;

    s_duration = side_PWM();
    s_distance = 0.0343 * s_duration / 2.0;

    return s_distance;
}

double ReadUltrasonic_Filt(void)
{
	double distance_nofilt;
	static double avg_filt_buf[FILT_SIZE] = {0,};
	static int old_index = 0;
	double distance_filt;
	static int sensorRxCnt = 0;

	distance_nofilt = ReadUltrasonic_noFilt();

	++old_index;
	old_index %= FILT_SIZE;  // Buffer Size = 5
	avg_filt_buf[old_index] = distance_nofilt;
	sensorRxCnt++;

	/* Calculate Moving Average Filter */
	if (sensorRxCnt >= FILT_SIZE) {
		double sum = 0;
		for (int i = 0; i < FILT_SIZE; i++) { sum += avg_filt_buf[i]; }
		distance_filt = sum / FILT_SIZE;
	}
	else
		distance_filt = distance_nofilt;

	return distance_filt;
}

