/**********************************************************************************************************************
 * \file GTM_HANDLE.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE. *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_HANDLE.h"

#include "BSP.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_ATOM       40                                  /* Interrupt priority number                        */
#define HANDLE                  IfxGtm_ATOM1_6_TOUT16_P00_7_OUT     /* P20_1 is servo_1                                 */
#define CLK_FREQ                1000000.0f                          /* CMU clock frequency, in Hertz                    */
#define SERVO_PWM_PERIOD        10000                               /* PWM period for the ATOM, in ticks                */

#define DEGREE_0                650
#define DEGREE_180              2350
#define NEUTRAL                 1500

#define MAX_RPM                 100.0F          //need MAX RPM

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Atom_Pwm_Config h_atomConfig;                            /* Timer configuration structure                    */
IfxGtm_Atom_Pwm_Driver h_atomDriver;                            /* Timer Driver structure                           */\
volatile uint32 Hcurr = 0;

float32_t steering_Angle = 0;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the ATOM */
void initHANDLEServo(void)
{
    IfxGtm_enable(&MODULE_GTM);                                             /* Enable GTM                           */

    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ);    /* Set the CMU clock 0 frequency        */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);            /* Enable the CMU clock 0               */

    IfxGtm_Atom_Pwm_initConfig(&h_atomConfig, &MODULE_GTM);                 /* Initialize default parameters        */

    h_atomConfig.atom = HANDLE.atom;                                         /* Select the ATOM depending on the LED     */
    h_atomConfig.atomChannel = HANDLE.channel;                               /* Select the channel depending on the LED  */
    h_atomConfig.period = SERVO_PWM_PERIOD;                                 /* Set timer period                         */
    h_atomConfig.pin.outputPin = &HANDLE;                                    /* Set LED as output                        */
    h_atomConfig.synchronousUpdateEnabled = TRUE;                           /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&h_atomDriver, &h_atomConfig);                     /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&h_atomDriver, TRUE);                             /* Start the PWM                            */

    Hcurr = NEUTRAL;
    updateHANDLEServoDuty(Hcurr);
}

void HandleAngle(float32_t RPM_Diff){
    steering_Angle = (RPM_Diff / MAX_RPM)  * 90;

    int HPWM = 650+((steering_Angle + 90) / 180) * (2350-650);

    if(HPWM < DEGREE_0) HPWM = DEGREE_0;
    if(HPWM > DEGREE_180) HPWM = DEGREE_180;

    updateHANDLEServoDuty(HPWM);
}

/* This function sets the duty cycle of the PWM */
void setHANDLEDuty(uint32 dutyCycle)
{
    h_atomConfig.dutyCycle = dutyCycle;                 /* Set duty cycle                                           */
    IfxGtm_Atom_Pwm_init(&h_atomDriver, &h_atomConfig); /* Re-initialize the PWM                                    */
}

void updateHANDLEServoDuty(int newCurr) {
    Hcurr = newCurr;      //update curr value
    setHANDLEDuty(Hcurr);  //setting PWM signal
}
