/**********************************************************************************************************************
 * \file GTM_ATOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_SERVO.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_ATOM       10                                  /* Interrupt priority number                        */
#define SERVO                   IfxGtm_ATOM1_2_TOUT12_P00_3_OUT     /* P20_1 is servo_1                                 */
#define CLK_FREQ                1000000.0f                          /* CMU clock frequency, in Hertz                    */
#define SERVO_PWM_PERIOD        10000                               /* PWM period for the ATOM, in ticks                */
#define DEGREE_0                650
#define DEGREE_45               1050
#define DEGREE_135              1950
#define DEGREE_180              2350
#define NEUTRAL                 1500
#define FSWING                  1385        //값 테스트 필요
#define BSWING                  1615
#define STEP                    2                                   //us
#define DEL_TIME                1000000                             //10ms


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Atom_Pwm_Config s_atomConfig;                            /* Timer configuration structure                    */
IfxGtm_Atom_Pwm_Driver s_atomDriver;                            /* Timer Driver structure                           */\
volatile uint32 curr = 0;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the ATOM */
void initGtmServo(void)
{
    IfxGtm_enable(&MODULE_GTM);                                             /* Enable GTM                           */

    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ);    /* Set the CMU clock 0 frequency        */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);            /* Enable the CMU clock 0               */

    IfxGtm_Atom_Pwm_initConfig(&s_atomConfig, &MODULE_GTM);                 /* Initialize default parameters        */

    s_atomConfig.atom = SERVO.atom;                                         /* Select the ATOM depending on the LED     */
    s_atomConfig.atomChannel = SERVO.channel;                               /* Select the channel depending on the LED  */
    s_atomConfig.period = SERVO_PWM_PERIOD;                                 /* Set timer period                         */
    s_atomConfig.pin.outputPin = &SERVO;                                    /* Set LED as output                        */
    s_atomConfig.synchronousUpdateEnabled = TRUE;                           /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&s_atomDriver, &s_atomConfig);                     /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&s_atomDriver, TRUE);                             /* Start the PWM                            */

    curr = NEUTRAL;
    updateCurrAndSetServoDuty(curr);
}

void seatSwing(int flag){
    static int direction = 1;

    if(flag == 3){
        if(curr >= BSWING){
            direction = -1;
            curr = FSWING;
        }
        else if(curr <= FSWING) {
            direction = 1;
            curr = BSWING;
        }
        else {
            curr = FSWING;      //NEUTRAL시 처리 플래그?
        }
        updateCurrAndSetServoDuty(curr);
    }
}

/* This function sets the duty cycle of the PWM */
void setServoDuty(uint32 dutyCycle)
{
    s_atomConfig.dutyCycle = dutyCycle;                 /* Set duty cycle                                           */
    IfxGtm_Atom_Pwm_init(&s_atomDriver, &s_atomConfig); /* Re-initialize the PWM                                    */
}

void updateCurrAndSetServoDuty(int newCurr) {
    curr = newCurr;      //update curr value
    setServoDuty(curr);  //setting PWM signal
}
