/**********************************************************************************************************************
 * \file ULTRA_FILT.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <ULTRA_FILT.h>
#include "ASW/BCW.h"
#include <math.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ALPHA 0.4F
#define ult_noise 8000.F

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static float32 kmfRESULT = 0.0F;
static float32 LPF = 0.0F;
static char firstFlag = 0;
static char mfFlag = 0;
const float32 ALLOWED_CHANGE = 100.0;

static float32 KF = 0.0;
static float32 MF = 0.0;
static float32 durr = 0.0F;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

UKFilter kmf;
MFilter mf;

float32 low_pass_filter(float32 new_value, float32 dur){
    static float32 prev_value = 0.0F;

    if(LPF == 0.0F){
        LPF = new_value;
        prev_value = LPF;
    }
    else{
        LPF = (ALPHA * new_value) + ((1.0F - ALPHA) * LPF);
    }

    float32 deltaL = fabsf(new_value - prev_value);
    if(deltaL > ALLOWED_CHANGE){
        LPF = prev_value;
    }

    if(firstFlag == 0){
        firstFlag = 1;
        km_init(&kmf, LPF, ult_noise);
    }
    KF = km_update(&kmf, LPF);

    prev_value = new_value;

    durr = dur;

    return LPF;
}

void km_init(UKFilter *kmf, float32 init_x, float32 u_noise) {
    kmf->x = init_x;                                      // initial position
    kmf->p = 1000.0F;                                        // initial uncertainty
    kmf->q = 0.00005F;                                          // sensor process noise(uncertainty of estimated value)
    kmf->r = u_noise;                                        // measurement noise
}

float32 km_update(UKFilter *kmf, float32 Z) {
    // predict step
    float32 X_pred = kmf->x;                               // position predict
    float32 P_pred = kmf->p + kmf->q;                       // covariance predict

    // kalman gain calculate
    float32 K = P_pred / (P_pred + kmf->r);

    //update step
    kmf->x = X_pred + K * (Z - X_pred);                      // estimated value revision
    kmf->p = (1.0F - K) * P_pred;                            //covariance update
    kmfRESULT = kmf->x;

    update_median_filter(&mf, kmfRESULT);

    //BCW active
    Back_Collision_Warning(MF, durr);

    return kmfRESULT;
}

static void selection_sort(float32 arr[], uint32_t size){
    uint32_t minIdx = 0;

    for(int i = 0; i < (size-1); i++){
        minIdx = i;
        for(int j = (i+1); j < size; j++){
            if(arr[j] < arr[minIdx]){
                minIdx = j;
            }
        }

        float32 temp = arr[i];
        arr[i] = arr[minIdx];
        arr[minIdx] = temp;
    }
}

static float32 get_median_val(const MFilter* mf){
    float32 sortedVal[WINDOW_SIZE];

    for(int i=0; i<WINDOW_SIZE; i++){
        sortedVal[i] = mf->values[i];
    }
    selection_sort(sortedVal, WINDOW_SIZE);

    MF = sortedVal[WINDOW_SIZE/2U];

    return MF;
}

static float32 update_median_filter(MFilter* mf, float32 kfr){
    if(mfFlag == 0){
        for(int i = 0; i < WINDOW_SIZE; i++){
            mf->values[i] = kfr;
        }
        mfFlag = 1;
    }

    for(int i=0; i<WINDOW_SIZE-1; i++){
        mf->values[i] = mf->values[i+1];
    }
    mf->values[WINDOW_SIZE-1] = kfr;

    return get_median_val(mf);
}

uint16_t get_ult_val(void){
    return (uint16_t)MF;
}



