/**********************************************************************************************************************
 * \file ULTRA_FILT.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <ULTRA_FILT.h>
//#include "ASW/BCW.h"
#include <math.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ALPHA 0.1F
#define MAX_THRESHOLD 50.0F
#define MEDIAN_WINDOW_SIZE 6
#define ult_noise 50000.F

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static float32 median_buffer[MEDIAN_WINDOW_SIZE] = {0};
static float32 kmfRESULT = 0.0;
static float32 KMF = 0.0;

static int mIndex = 0;

static char flagg = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

UKFilter kmf;

void km_init(UKFilter *kmf, float32 init_x, float32 u_noise) {
    kmf->x = init_x;                                      // initial position
    kmf->p = 1000.0F;                                        // initial uncertainty
    kmf->q = 0.0001F;                                          // sensor process noise(uncertainty of estimated value)
    kmf->r = u_noise;                                        // measurement noise
}

float32 km_update(UKFilter *kmf, float32 Z) {
    // predict step
    float32 X_pred = kmf->x;                               // position predict
    float32 P_pred = kmf->p + kmf->q;                       // covariance predict

    // kalman gain calculate
    float32 K = P_pred / (P_pred + kmf->r);

    //update step
    kmf->x = X_pred + K * (Z - X_pred);                      // estimated value revision
    kmf->p = (1.0F - K) * P_pred;                            //covariance update
    kmfRESULT = kmf->x;

    return kmfRESULT;
}

float32 median_filter(float32 new_value, float32 dur) {
    float32 MF = 0.0;
    float32 sorted[MEDIAN_WINDOW_SIZE], temp;

    median_buffer[mIndex] = new_value;
    mIndex = (mIndex + 1) % MEDIAN_WINDOW_SIZE;

    for (int i = 0; i < MEDIAN_WINDOW_SIZE; i++) {
        sorted[i] = median_buffer[i];
    }
    for (int i = 0; i < (MEDIAN_WINDOW_SIZE - 1); i++) {
        for (int j = 0; j < (MEDIAN_WINDOW_SIZE - i - 1); j++) {
            if (sorted[j] > sorted[j + 1]) {
                temp = sorted[j];
                sorted[j] = sorted[j + 1];
                sorted[j + 1] = temp;
            }
        }
    }

    MF = sorted[MEDIAN_WINDOW_SIZE / 2];
    if(flagg == 0){
        flagg = 1;
        km_init(&kmf, MF, ult_noise);
    }
    KMF = km_update(&kmf, MF);
    //Back_Collision_Warning(KMF, dur);

    return MF;
}

uint16_t get_ult_val(void){
    return (uint16_t)kmfRESULT;
}
