/**********************************************************************************************************************
 * \file BCW.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <BCW.h>
#include <BSW_Filter/ULTRA_FILT.h>
#include <BSW_Sensor/Ultrasonic.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define DIST_THR 300.0F
#define usToSec 100000.0F


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static float32 t1 = 0.0F;
static float32 t2 = 0.0F;
static float32 L1 = 0.0F;                     //C*t1/2
static float32 L2 = 0.0F;                     //C*t2/2

static const float32 VA = 18.0F;
static float32 VB = 0.0F;
static float32 tcr = 0.0F;                    //L2/(VB-BA)
static const float32 tex = 3.0F;
static const float32 alpha = 0.5F;                  //need calculate?
static const float32 car_length = 257.0F;

static char first_flag = 0;

static char WARN_FLAG = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/*받아야 하는 정보: 각 시점의 거리값, 각 시점의 초음파 복귀시간, 현재 속도, 후행 차량의 속도, 차선 변경 예상소요시간*/

/*
 * 현재 제대로 작동X BCW 수정 필요함
 *
 */
char Back_Collision_Warning(float32 distance, float32 measure){

    L2 = distance;
    t2 = measure;

    if(first_flag == 0) {
        L1 = L2;
        t1 = t2;
        first_flag = 1;
    }

    if(fabsf(L2 - L1) > DIST_THR) {
        L1 = L2;
        t1 = t2;
    }

    VB = VA + (L2-L1)/((t2-t1)*usToSec);

    if(fabsf(VB - VA) < 0.0001F){
        return WARN_FLAG;
    }

    tcr = L2/(VB-VA);

    if(tex < tcr){
        WARN_FLAG = 0;
    } else if (tex > tcr && L2 < 1000){
        WARN_FLAG = 1;
    } else {
        if(L2 < (1+alpha) * car_length){
            WARN_FLAG = 1;
        } else {
            WARN_FLAG = 0;
        }
    }

    return WARN_FLAG;
}

char get_BCW_Flag(void){
    return WARN_FLAG;
}
